### ISSUE TITLE
Error in configuration instructions

### ISSUE THREAD

**Issue by jegesh** [shannah/cn1-css#2]
The instructions suggest adding to our code the following line: `UIManager.getInstance().addThemeProps(css.getThemeResourceNames()[0]);`.

However, `addThemeProps()` needs to receive a `Hashtable` not a `String`, which is what is returned by `getThemeResourceNames()`.  What's the correct params for `addThemeProps` here?

**Comment by shannah** [comment]
Thanks.  It is fixed now.  It should read

~~~
UIManager.getInstance().addThemeProps(css.getTheme(css.getThemeResourceNames()[0]));
~~~

**Comment by jegesh** [comment]
Hey, Steve, you are quick!
