### ISSUE TITLE
CN1CSSCompileTask : Unsupported major.minor version

### ISSUE THREAD

**Issue by MoKamal** [shannah/cn1-css#3]
Having followed the Readme and when trying to compile using Netbeans 8.1 with JDK 8, I (Oracle) get the following:

**build.xml:493: java.lang.UnsupportedClassVersionError: com/codename1/ui/css/CN1CSSCompileTask : Unsupported major.minor version 52.0**

Can you advice as to what might be the causes??

**Comment by shannah** [comment]
It may have been compiled with JDK 8.  Are you running JDK 7 or JDK 8?

**Comment by MoKamal** [comment]
jdk1.8.0_91 was added to the Netbeans platforms and setup the Java Platform this,

Do I also need to setup the Java_Home Classpath under the System variables??

**Comment by shannah** [comment]
Are you using the "build from source" instructions?  i.e. running "ant jar" on the command line, or this this another part of the instructions.

In any case, somehow it is using an older java to run this.  Is build.xml line 493, part of your Codename One project's build.xml file?

Also check the version of the JDK that you are using for the project (if running inside Netbeans build).  (I.e. Properties > Libraries > Java Platform)

**Comment by MoKamal** [comment]
I am using the downloaded binary, I also verified the JDK 8 with 86 and 64 in addition to setting the JAVA_HOME classpath, yet it's the same issue on Windows 8 machine,
build.xml is part of my CN1 project, which was modified for CNS CSS Lib as per your instruction:

    
    <taskdef name="compileCSS"
             classname="com.codename1.ui.css.CN1CSSCompileTask"
             classpath="lib/cn1css-ant-task.jar"/>

    <target name="compile-css">
        <compileCSS/>
    </target>   
And updated to 
<target name="-pre-compile" depends="compile-css">

**Comment by shannah** [comment]
The CN1CSSCompileTask uses the `<java>` ant task to fork a java process.  This will be the equivalent of basically calling `java` in the command line.

Try opening a command prompt and type
`java -version`

And see what happens.

**Comment by MoKamal** [comment]
Hi Steve, thank you but I already did that, and below is the output from the CMD:

**Comment by MoKamal** [comment]
C:\Users\DELL 5559>java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by shannah** [comment]
Check the version of Java that Netbeans is running on.  Select "About Netbeans" to get a box that looks like this:

![image](https://cloud.githubusercontent.com/assets/2677562/14898465/b8427816-0d3b-11e6-9fdf-80b121a6f38a.png)

**Comment by MoKamal** [comment]
As you correctly deduced, Netbeans's runtime is using 1.7: Product Version: NetBeans IDE 8.1 (Build 201510222201)
Updates: Updates available to version NetBeans 8.1 Patch 1
Java: 1.7.0_79; Java HotSpot(TM) Client VM 24.79-b02
Runtime: Java(TM) SE Runtime Environment 1.7.0_79-b15
System: Windows 8 version 6.2 running on x86; Cp1252; en_US (nb)
User directory: C:\Users\...\AppData\Roaming\NetBeans\8.1
Cache directory: C:\Users\...\AppData\Local\NetBeans\Cache\8.1

**Comment by MoKamal** [comment]
Steve, thank you, that was fixed by updating the "netbeans_jdkhome" value on netbeans.conf, just one thought came to mind ... Would it be possible to make the CN1 CSS Library use the Project’s runtime instead of the Netbeans runtime and hopefully avoid any concerns when it comes to a multiple projects with specific runtime requirements?

**Comment by shannah** [comment]
Most ant tasks are set to run in the environment of Netbeans.  Making it run in the platform for the particular project may be even more confusing.

I'll look through my sources and see if I'm actually using any Java 8 apis.  If it is easy to switch I may make a java 7 binary.  Alternatively I might just do a check for the java version and make a clearer error message if you don't have the right version.
