### ISSUE TITLE
about installation

### ISSUE THREAD

**Issue by crim94** [shannah/cn1-css#4]
Hi steve ,i followed all instructions : i have downloaded "cn1css-ant-task.jar" and i have put into the lib folder and i modified the xml file as you have been mentioned ,but when i compile the project ,the css.res file is not generated and i get an exception :( can you help me ! 
(sorry for my poor english :p i speak french ) (y)

**Comment by shannah** [comment]
Please post the exception and stack trace.

**Comment by crim94** [comment]
java.io.IOException: /style.css.res not found
	at com.codename1.ui.util.Resources.open(Resources.java:727)
	at com.codename1.ui.util.Resources.openLayered(Resources.java:694)
	at com.codename1.ui.util.Resources.openLayered(Resources.java:658)
	at com.cn1.connectivite.Connectivite.init(Connectivite.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.codename1.impl.javase.Executor$1$1.run(Executor.java:81)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1151)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:968)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
==> this the fragment of code that cause this prob : 
Resources css;
        try {
            css = Resources.openLayered("/style.css");
            UIManager.getInstance().addThemeProps(css.getTheme(css.getThemeResourceNames()[0]));
          
        } catch (IOException ex) {
            ex.printStackTrace();
            Dialog.show("exception", ex.getMessage(),"ok",null);
        }
 
style.css : this my stylesheet name it is under src

**Comment by shannah** [comment]
style.css should go in the "css" directory.  Not src.  The css ant task will detect it there, and compile it into a file named style.css.res, which it will place in your "src" directory.

**Comment by crim94** [comment]
i created a folder css under my project and i moved the css file in this folder but i still get the some errors : 
java.io.IOException: /style.css.res not found
	at com.codename1.ui.util.Resources.open(Resources.java:727)
	at com.codename1.ui.util.Resources.openLayered(Resources.java:694)
	at com.codename1.ui.util.Resources.openLayered(Resources.java:658)
	at com.cn1.connectivite.Connectivite.init(Connectivite.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.codename1.impl.javase.Executor$1$1.run(Executor.java:81)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1151)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:968)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

**Comment by shannah** [comment]
What IDE?  (Netbeans of Eclipse)
Where did you create the css directory?  It should be in the root of the project.  Not inside the "src" directory.. it should the same parent as the "src" directory.
Did any *.res files get created and added to your src directory when you built the project?

**Comment by crim94** [comment]
I work with Netbeans ,
 the css folder is in the root of the project in the some level as src and lib .... 
no there is no file .res  generated after the build

**Comment by shannah** [comment]
Sounds like it isn't even running the css lib.  Please review the install steps and make sure you that you have added it correctly in your build.xml file.

If you still can't get it working, post both the build.xml file and the console output from the build.

**Comment by crim94** [comment]
I applied the instructions in wiki i will review it ,but I tested your project (css demo ) it works but when i add a new css file in the css folder the res file of this new stylesheet doesn't appear

**Comment by crim94** [comment]
this is my build.xml file : 


<?xml version="1.0" encoding="UTF-8"?>
    
    
        
    <project name="Connectivite" default="default" basedir=".">
    <description>Builds, tests, and runs the project Connectivite.</description>
    <import file="nbproject/build-impl.xml"/>
    <property file="codenameone_settings.properties"/>
    <property name="automated" value="false" />
    <taskdef name="codeNameOne" classname="com.codename1.build.client.CodeNameOneBuildTask" classpath="CodeNameOneBuildClient.jar"/>
    <taskdef name="compileCSS"
        classname="com.codename1.ui.css.CN1CSSCompileTask"
        classpath="lib/cn1css-ant-task.jar"/>
    
    <target name="compile-css">
        <compileCSS/>
    </target>  
    <taskdef name="prepareTests" classname="com.codename1.build.client.PrepareTestsTask" classpath="CodeNameOneBuildClient.jar"/>
    <taskdef name="installLibs" classname="com.codename1.build.client.InstallLibsTask" classpath="CodeNameOneBuildClient.jar"/>
    <taskdef name="verifyDir" classname="com.codename1.build.client.VerifyDir" classpath="CodeNameOneBuildClient.jar"/>
    <taskdef name="generateGuiSources" classname="com.codename1.build.client.GenerateGuiSources" classpath="CodeNameOneBuildClient.jar"/>
    <taskdef name="initOfflineBuilder" classname="com.codename1.build.client.InitOfflineBuilder" classpath="CodeNameOneBuildClient.jar"/>

    <target depends="init,compile,jar" name="compile-test">
        <mkdir dir="${build.test.classes.dir}" />
        <mkdir dir="${test.src.dir}" />
        <javac destdir="${build.test.classes.dir}"
            encoding="${source.encoding}"
            source="1.8"
            target="1.8"
            bootclasspath="CLDC11.jar" excludes="${excludes}"
            classpath="${javac.classpath}:${build.classes.dir}">
            <src path="${test.src.dir}"/>
        </javac>        
        <prepareTests classesDir="${build.classes.dir}" testClassesDir="${build.test.classes.dir}" seJar="JavaSE.jar" metaDataFile="${build.test.classes.dir}/tests.dat" />
        <jar jarfile="dist/unitTests.jar">
            <fileset dir="${build.classes.dir}"/>
            <fileset dir="${build.test.classes.dir}"/>
            <fileset dir="lib/impl/cls"/>
        </jar>
    </target>

    <target depends="compile-test" name="-do-test-run">        
        
        <java classpath="dist/unitTests.jar:${javac.test.classpath}:${file.reference.JavaSE.jar}" classname="com.codename1.impl.javase.TestRunner">
            <arg value="${codename1.packageName}.${codename1.mainName}" />
        </java>
    </target>
    
    <target depends="-do-test-run" description="Run unit tests." name="test"/> 
<target name="-pre-compile"  depends="compile-css">
        <echo>Compile is forcing compliance to the supported API's/features for maximum device compatibility. This allows smaller
        code size and wider device support</echo>
        <mkdir dir="build/tmp"/>
        <javac destdir="build/tmp"
            encoding="${source.encoding}"
            source="1.8"
            target="1.8"
            bootclasspath="lib/CLDC11.jar" excludes="${excludes}"
            classpath="${javac.classpath}:${build.classes.dir}">
            <src path="${src.dir}"/>
        </javac>        
    </target>

    <target name="-post-compile">
        <delete>
            <fileset dir="${build.classes.dir}" includes="**/package-info.class"/>
        </delete>
        <delete>
            <fileset dir="${build.classes.dir}" includes="**/package-info.class"/>
        </delete>
        <delete>
            <fileset dir="${build.classes.dir}" includes="**/Thumbs.db"/>
        </delete>
    </target>

    <target name="build-for-ios-device" depends="clean,copy-ios-override,copy-libs,jar,clean-override">
        <codeNameOne 
            jarFile="${dist.jar}"
            displayName="${codename1.displayName}"
            packageName = "${codename1.packageName}"
            mainClassName = "${codename1.mainName}"
            version="${codename1.version}"
            icon="${codename1.icon}"
            vendor="${codename1.vendor}"
            subtitle="${codename1.secondaryTitle}"
            
            targetType="iphone"
            certificate="${codename1.ios.debug.certificate}"
            certPassword="${codename1.ios.debug.certificatePassword}"
            provisioningProfile="${codename1.ios.debug.provision}"
            appid="${codename1.ios.appid}"
            automated="${automated}"
            />
    </target>

    <target name="offline-builder-ios-debug" depends="clean,copy-ios-override,copy-libs,jar,clean-override">
        <initOfflineBuilder />
        <java jar="${selectedOfflineBuilder}">
            <arg value="ios" />
            <arg file="codenameone_settings.properties" />
            <arg file="${dist.jar}" />
        </java>
    </target>

    <target name="offline-builder-ios-release" depends="clean,copy-ios-override,copy-libs,jar,clean-override">
        <initOfflineBuilder />
        <java jar="${selectedOfflineBuilder}">
            <arg value="ios-release" />
            <arg file="codenameone_settings.properties" />
            <arg file="${dist.jar}" />
        </java>
    </target>

    <target name="offline-builder-android" depends="clean,copy-android-override,copy-libs,jar,clean-override">
        <initOfflineBuilder />
        <java jar="${selectedOfflineBuilder}">
            <arg value="and" />
            <arg file="codenameone_settings.properties" />
            <arg file="${dist.jar}" />
            <arg file="gradlePath" />
        </java>
    </target>

    <target name="test-for-ios-device" depends="clean,copy-ios-override,copy-libs,compile-test,clean-override">
        <codeNameOne 
            jarFile="dist/unitTests.jar"
            displayName="${codename1.displayName}"
            packageName = "${codename1.packageName}"
            mainClassName = "${codename1.mainName}"
            version="${codename1.version}"
            icon="${codename1.icon}"
            vendor="${codename1.vendor}"
            subtitle="${codename1.secondaryTitle}"
            buildArgs="build.unitTest=1"
            targetType="iphone"
            certificate="${codename1.ios.debug.certificate}"
            certPassword="${codename1.ios.debug.certificatePassword}"
            provisioningProfile="${codename1.ios.debug.provision}"
            appid="${codename1.ios.appid}"
            automated="${automated}"
            />
    </target>

    <target name="test-for-android-device" depends="clean,copy-android-override,copy-libs,compile-test,clean-override">
        <codeNameOne 
            jarFile="dist/unitTests.jar"
            displayName="${codename1.displayName}"
            packageName = "${codename1.packageName}"
            mainClassName = "${codename1.mainName}"
            version="${codename1.version}"
            icon="${codename1.icon}"
            vendor="${codename1.vendor}"
            subtitle="${codename1.secondaryTitle}"
            buildArgs="build.unitTest=1"
            targetType="android"
            keystoreAlias="${codename1.android.keystoreAlias}"
            keystore="${codename1.android.keystore}"
            certPassword="${codename1.android.keystorePassword}"
            automated="${automated}"
            />
    </target>

    <target name="test-for-rim-device" depends="clean,copy-rim-override,copy-libs,compile-test,clean-override">
        <codeNameOne 
            jarFile="dist/unitTests.jar"
            displayName="${codename1.displayName}"
            packageName = "${codename1.packageName}"
            mainClassName = "${codename1.mainName}"
            version="${codename1.version}"
            icon="${codename1.icon}"
            vendor="${codename1.vendor}"
            subtitle="${codename1.secondaryTitle}"
            buildArgs="build.unitTest=1"
            targetType="rim"
            sigtoolDb="${codename1.rim.signtoolDb}"
            certPassword="${codename1.rim.certificatePassword}"
            sigtoolCsk="${codename1.rim.signtoolCsk}"
            automated="${automated}"
            />
        <delete>
            <fileset dir="${build.classes.dir}" includes="**/*.class"/>
        </delete>
    </target>

     <target name="test-for-j2me-device" depends="clean,j2me-native-theme-init,copy-j2me-native,copy-j2me-override,copy-libs,compile-test,clean-j2me-native,clean-override">
        <codeNameOne
            jarFile="dist/unitTests.jar"
            displayName="${codename1.displayName}"
            packageName = "${codename1.packageName}"
            mainClassName = "${codename1.mainName}"
            version="${codename1.version}"
            icon="${codename1.icon}"
            vendor="${codename1.vendor}"
            subtitle="${codename1.secondaryTitle}"
            targetType="me"            
            buildArgs="build.unitTest=1"
            automated="${automated}"
            />
        <delete>
            <fileset dir="${build.classes.dir}" includes="**/*.class"/>
        </delete>
    </target>

    
    <target name="build-for-ios-device-release" depends="clean,copy-ios-override,copy-libs,jar,clean-override">
        <codeNameOne 
            jarFile="${dist.jar}"
            displayName="${codename1.displayName}"
            packageName = "${codename1.packageName}"
            mainClassName = "${codename1.mainName}"
            version="${codename1.version}"
            icon="${codename1.icon}"
            vendor="${codename1.vendor}"
            subtitle="${codename1.secondaryTitle}"
            appStoreBuild="true"
            production="true"
            targetType="iphone"
            certificate="${codename1.ios.release.certificate}"
            certPassword="${codename1.ios.release.certificatePassword}"
            provisioningProfile="${codename1.ios.release.provision}"
            appid="${codename1.ios.appid}"
            automated="${automated}"
            />
    </target>

    <target name="copy-libs" depends="init">
        <copy todir="${build.classes.dir}">
            <fileset dir="lib/impl/cls" />
        </copy>
    </target>

    <target name="copy-android-override">
        <mkdir dir="${build.classes.dir}" />
        <mkdir dir="override" />
        <copy todir="${build.classes.dir}">
            <fileset dir="override" includes="**/*_android.ovr"/>
            <fileset dir="override" includes="**/*_android-phone.ovr"/>
            <fileset dir="override" includes="**/*_android-tab.ovr"/>
            <fileset dir="override" includes="**/*_phone.ovr"/>
            <fileset dir="override" includes="**/*_tablet.ovr"/>
        </copy>
        <copy todir="${build.classes.dir}">
            <fileset dir="native/android" includes="**/*"/>
            <fileset dir="lib/impl/native/android" includes="**/*"/>
        </copy>
    </target>
    
    <target name="copy-ios-override">
        <mkdir dir="${build.classes.dir}" />
        <mkdir dir="override" />
        <copy todir="${build.classes.dir}">
            <fileset dir="override" includes="**/*_ios.ovr"/>
            <fileset dir="override" includes="**/*_iphone.ovr"/>
            <fileset dir="override" includes="**/*_ipad.ovr"/>
            <fileset dir="override" includes="**/*_phone.ovr"/>
            <fileset dir="override" includes="**/*_tablet.ovr"/>
        </copy>
        <copy todir="${build.classes.dir}">
            <fileset dir="native/ios" includes="**/*"/>
            <fileset dir="lib/impl/native/ios" includes="**/*"/>
        </copy>
    </target>
        
    <target name="copy-javascript-override">
        <mkdir dir="${build.classes.dir}" />
        <mkdir dir="override" />
        <mkdir dir="native/javascript" />
        <mkdir dir="lib/impl/native/javascript" />
        <copy todir="${build.classes.dir}">
            <fileset dir="native/javascript" includes="**/*"/>
            <fileset dir="lib/impl/native/javascript" includes="**/*"/>
        </copy>
    </target>
    
    <target name="copy-rim-override">
        <mkdir dir="${build.classes.dir}" />
        <mkdir dir="override" />
        <copy todir="${build.classes.dir}">
            <fileset dir="override" includes="**/*_rim.ovr"/>
            <fileset dir="override" includes="**/*_phone.ovr"/>
        </copy>
        <copy todir="${build.classes.dir}">
            <fileset dir="native/rim" includes="**/*"/>
            <fileset dir="lib/impl/native/rim" includes="**/*"/>
        </copy>
    </target>

    <target name="copy-desktop-override">
        <mkdir dir="${build.classes.dir}" />
        <mkdir dir="override" />
        <mkdir dir="lib/impl/native/javase" />
        <copy todir="${build.classes.dir}">
            <fileset dir="override" includes="**/*_tablet.ovr"/>
            <fileset dir="override" includes="**/*_desktop.ovr"/>
        </copy>
        <copy todir="${build.classes.dir}">
            <fileset dir="native/javase" includes="**/*"/>
            <fileset dir="lib/impl/native/javase" includes="**/*"/>
        </copy>
    </target>

    <target name="copy-j2me-override">
        <mkdir dir="${build.classes.dir}" />
        <mkdir dir="override" />
        <copy todir="${build.classes.dir}">
            <fileset dir="override" includes="**/*_me.ovr"/>
            <fileset dir="override" includes="**/*_phone.ovr"/>
        </copy>
        <copy todir="${build.classes.dir}">
            <fileset dir="native/j2me" includes="**/*"/>
            <fileset dir="lib/impl/native/j2me" includes="**/*"/>
        </copy>
    </target>

    <target name="clean-override">
        <delete>
            <fileset dir="${build.classes.dir}" includes="**/*.ovr"/>
            <fileset dir="${build.classes.dir}" includes="**/*.java"/>
            <fileset dir="${build.classes.dir}" includes="**/*.m"/>
            <fileset dir="${build.classes.dir}" includes="**/*.h"/>
        </delete>
    </target>
    
    <target name="build-for-android-device" depends="clean,copy-android-override,copy-libs,jar,clean-override">
        <codeNameOne 
            jarFile="${dist.jar}"
            displayName="${codename1.displayName}"
            packageName = "${codename1.packageName}"
            mainClassName = "${codename1.mainName}"
            version="${codename1.version}"
            icon="${codename1.icon}"
            vendor="${codename1.vendor}"
            subtitle="${codename1.secondaryTitle}"
            
            targetType="android"
            keystoreAlias="${codename1.android.keystoreAlias}"
            keystore="${codename1.android.keystore}"
            certPassword="${codename1.android.keystorePassword}"
            automated="${automated}"
            />
    </target>

    <target name="build-for-javascript" depends="clean,copy-javascript-override,copy-libs,jar,clean-override">
        <codeNameOne 
            jarFile="${dist.jar}"
            displayName="${codename1.displayName}"
            packageName = "${codename1.packageName}"
            mainClassName = "${codename1.mainName}"
            version="${codename1.version}"
            icon="${codename1.icon}"
            vendor="${codename1.vendor}"
            subtitle="${codename1.secondaryTitle}"
            
            targetType="javascript"
            automated="${automated}"
            />
    </target>    
    
    <target name="build-for-rim-device" depends="clean,copy-rim-override,copy-libs,jar,clean-override">
        <codeNameOne 
            jarFile="${dist.jar}"
            displayName="${codename1.displayName}"
            packageName = "${codename1.packageName}"
            mainClassName = "${codename1.mainName}"
            version="${codename1.version}"
            icon="${codename1.icon}"
            vendor="${codename1.vendor}"
            subtitle="${codename1.secondaryTitle}"

            targetType="rim"
            sigtoolDb="${codename1.rim.signtoolDb}"
            certPassword="${codename1.rim.certificatePassword}"
            sigtoolCsk="${codename1.rim.signtoolCsk}"
            automated="${automated}"
            />
        <delete>
            <fileset dir="${build.classes.dir}" includes="**/*.class"/>
        </delete>
    </target>

    <target name="build-for-mac-os-x-desktop" depends="clean,copy-desktop-override,copy-libs,jar,clean-override">
        <codeNameOne 
            jarFile="${dist.jar}"
            displayName="${codename1.displayName}"
            packageName = "${codename1.packageName}"
            mainClassName = "${codename1.mainName}"
            version="${codename1.version}"
            icon="${codename1.icon}"
            vendor="${codename1.vendor}"
            subtitle="${codename1.secondaryTitle}"

            targetType="desktop_macosx"
            automated="${automated}"
            />
        <delete>
            <fileset dir="${build.classes.dir}" includes="**/*.class"/>
        </delete>
    </target>
    
    <target name="build-for-windows-desktop" depends="clean,copy-desktop-override,copy-libs,jar,clean-override">
        <codeNameOne 
            jarFile="${dist.jar}"
            displayName="${codename1.displayName}"
            packageName = "${codename1.packageName}"
            mainClassName = "${codename1.mainName}"
            version="${codename1.version}"
            icon="${codename1.icon}"
            vendor="${codename1.vendor}"
            subtitle="${codename1.secondaryTitle}"

            targetType="desktop_windows"
            automated="${automated}"
            />
        <delete>
            <fileset dir="${build.classes.dir}" includes="**/*.class"/>
        </delete>
    </target>

    <target name="build-for-j2me-device" depends="clean,j2me-native-theme-init,copy-j2me-native,copy-j2me-override,copy-libs,jar,clean-j2me-native,clean-override">
        <codeNameOne
            jarFile="${dist.jar}"
            displayName="${codename1.displayName}"
            packageName = "${codename1.packageName}"
            mainClassName = "${codename1.mainName}"
            version="${codename1.version}"
            icon="${codename1.icon}"
            vendor="${codename1.vendor}"
            subtitle="${codename1.secondaryTitle}"
            targetType="me"            
            automated="${automated}"
            />
        <delete>
            <fileset dir="${build.classes.dir}" includes="**/*.class"/>
        </delete>
    </target>
      
    <target name="j2me-native-theme-init">
        <available file="${codename1.j2me.nativeTheme}" property="j2me-native-theme.available" />
    </target>
    
    <target name="copy-j2me-native" if="j2me-native-theme.available">
        <copy file="${codename1.j2me.nativeTheme}" tofile="src/nativeJ2METheme.res" />
    </target>

    <target name="clean-j2me-native" if="j2me-native-theme.available">
        <delete file="src/nativeJ2METheme.res" />
    </target>
      
    <target name="-pre-init">
        <property name="application.args" value="${codename1.packageName}.${codename1.mainName}"/>
        <property name="javac.source" value="1.8" />
        <property name="javac.target" value="1.8" />
        <mkdir dir="native/javase" />
        <mkdir dir="native/android" />
        <mkdir dir="native/internal_tmp" />
        <mkdir dir="native/ios" />
        <mkdir dir="native/j2me" />
        <mkdir dir="native/rim" />
        <mkdir dir="native/win" />
        <mkdir dir="native/javascript" />
        <mkdir dir="lib/impl/cls" />
        <mkdir dir="lib/impl/stubs" />
        <mkdir dir="lib/impl/native" />
        <mkdir dir="lib/impl/native/android" />
        <mkdir dir="lib/impl/native/ios" />
        <mkdir dir="lib/impl/native/j2me" />
        <mkdir dir="lib/impl/native/rim" />
        <mkdir dir="lib/impl/native/win" />
        <mkdir dir="lib/impl/native/javascript" />
        <installLibs lib="lib" dest="lib/impl" />
        <generateGuiSources srcDir="src" encoding="UTF-8" guiDir="res/guibuilder"  />
    </target>

    <target name="-post-jar">
        <mkdir dir="native/javase" />
        <mkdir dir="native/internal_tmp" />
        <mkdir dir="lib/impl/native/javase" />
        <javac destdir="native/internal_tmp"
            encoding="${source.encoding}"
            source="1.8"
            target="1.8"
            bootclasspath="CLDC11.jar" excludes="${excludes}"
            classpath="${javac.classpath}:${build.classes.dir}">
            <src path="native/javase"/>
            <src path="lib/impl/native/javase"/>
        </javac>        
    </target>

    <target name="-post-clean" depends="refresh-libs">
    </target>

    <target name="refresh-libs">
        <delete dir="lib/impl" />
        <installLibs lib="lib" dest="lib/impl" />        
    </target>

    <target name="copy-windows-override">
        <mkdir dir="${build.classes.dir}" />
        <mkdir dir="override" />
        <copy todir="${build.classes.dir}">
            <fileset dir="override" includes="**/*_win.ovr"/>
            <fileset dir="override" includes="**/*_win-phone.ovr"/>
            <fileset dir="override" includes="**/*_win-tab.ovr"/>
            <fileset dir="override" includes="**/*_phone.ovr"/>
            <fileset dir="override" includes="**/*_tablet.ovr"/>
        </copy>
        <mkdir dir="native/win" />
        <copy todir="${build.classes.dir}">
            <fileset dir="native/win" includes="**/*"/>
            <fileset dir="lib/impl/native/win" includes="**/*"/>
        </copy>
    </target>

    <target name="build-for-win-device" depends="clean,copy-windows-override,copy-libs,jar,clean-override">
        <codeNameOne 
            jarFile="${dist.jar}"
            displayName="${codename1.displayName}"
            packageName = "${codename1.packageName}"
            mainClassName = "${codename1.mainName}"
            version="${codename1.version}"
            icon="${codename1.icon}"
            vendor="${codename1.vendor}"
            subtitle="${codename1.secondaryTitle}"
            
            targetType="win"
            automated="${automated}"
            />
    </target>
                
    <target name="build-for-windows-device" depends="clean,copy-windows-override,copy-libs,jar,clean-override">
        <codeNameOne 
            jarFile="${dist.jar}"
            displayName="${codename1.displayName}"
            packageName = "${codename1.packageName}"
            mainClassName = "${codename1.mainName}"
            version="${codename1.version}"
            icon="${codename1.icon}"
            vendor="${codename1.vendor}"
            subtitle="${codename1.secondaryTitle}"
            
            certificate="${codename1.windows.certificate}"
            certPassword="${codename1.windows.certificatePassword}"

            targetType="windows"
            automated="${automated}"
            />
    </target>
                
    <target name="webservice-wizard">
        <java classpath="CodeNameOneBuildClient.jar" classname="com.codename1.ws.wizard.WSWizard" dir="." fork="true" />
    </target>
</project>

**Comment by shannah** [comment]
That looks right.  What was the build output?

**Comment by crim94** [comment]
ant -f C:\\Users\\criminel\\Documents\\NetBeansProjects\\Connectivite -Dnb.internal.action.name=build jar
No GUI Entries available
init:
Deleting: C:\Users\criminel\Documents\NetBeansProjects\Connectivite\build\built-jar.properties
deps-jar:
Updating property file: C:\Users\criminel\Documents\NetBeansProjects\Connectivite\build\built-jar.properties
compile-css:
sept. 07, 2016 7:56:47 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
class org.w3c.flute.util.Encoding: couldn't load encoding properties 
java.lang.NullPointerException
	at org.w3c.flute.util.Encoding.<clinit>(Encoding.java:40)
	at org.w3c.flute.parser.Parser.getCharStreamWithLurk(Parser.java:344)
	at org.w3c.flute.parser.Parser.parseStyleSheet(Parser.java:99)
	at com.codename1.ui.css.CSSTheme.load(CSSTheme.java:4552)
	at com.codename1.ui.css.CN1CSSCLI.main(CN1CSSCLI.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
RenderJob.run: internal exception
java.lang.NullPointerException
	at com.sun.javafx.tk.quantum.QuantumToolkit$5.run(QuantumToolkit.java:1403)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.lang.Thread.run(Thread.java:745)

**Comment by shannah** [comment]
Looks like an NPE inside the JavaFX pipeline.  What version of the JDK are you using?  If you can, try using a different JDK and see if that fixes it up.

Also, what does the contents of your style.css look like.  Try to make it as minimal as possible and see if it avoids this error.  It might be something specific in the stylesheet that is tripping up JavaFX.

**Comment by crim94** [comment]
finally it works :p i minimized my stylesheet us you said ,thanks Steve :+1:

**Comment by shannah** [comment]
Do you know what the problem was?  Was it a particular CSS property?

**Comment by crim94** [comment]
i don't know exactly ,the old stylesheet contains 300 lines i minimized and it works

**Comment by crim94** [comment]
i think that the problem is in border and his variant ,when i build my project and my stylesheet containes border or border-raduis ,i get an exception and a build failed as result but when i remove this properties i get the some exception and a successful build

**Comment by shannah** [comment]
The first exception actually is nothing.  It is the second NPE in QuantumToolkit that is something.

Can you post a snippet of the CSS that causes the problem?

**Comment by crim94** [comment]
this is my stylesheet ,when i remove border-radius it works
@font-face {
    font-family: "Source Sans Pro";
    src: url(github://google/fonts/blob/master/ofl/sourcesanspro/SourceSansPro-Light.ttf);
}
Button{
color:blue;
background-color: magenta;
width:50px;
border-radius: 20px;

   
}
Button.pressed{
     background-color: yellow;
}
TextField{
font-size:36px;
color:red;
text-align:center;

}
