### ISSUE TITLE
cn1-source-dpi doesn't work properly

### ISSUE THREAD

**Issue by jsfan3** [shannah/cn1-css#5]
Hello,
this is my Netbeans project, it's very simple (only one image and css):
[Test Image Size with CSS.zip](https://github.com/shannah/cn1-css/files/1212212/Test.Image.Size.with.CSS.zip)

Try to change cn1-source-dpi to 2000, 1500 and 1000: the size of the image in the simulator (with iphone3gs.skin) and in an Android device doesn't change. Of course, every time that I changed cn1-source-dpi, I deleted theme.css.res and clicked on "Clean and Build Project".

Is it a bug? Thank you for any help! :-)

**Comment by shannah** [comment]
I have added some documentation to the cn1-source-dpi directive to clarify how it works. 

https://github.com/shannah/cn1-css/wiki/Supported-Properties#custom-properties

Only the values 0, 120, 160, 320, 480 have meaning.
